within AdvancedReactor_sCO2_Library.Media;
package sCO2
  "Supercritical CO2 medium model — backed by tabulated CoolProp data"
  extends Modelica.Media.Interfaces.PartialPureSubstance(
    final mediumName     = "sCO2",
    final substanceNames = {"CO2"},
    final singleState    = false,
    final reducedX       = true,
    final fixedX         = true);

  // Reference state matches CoolProp default IIR reference for CO2.
  constant Modelica.Units.SI.Temperature T_crit = 304.13
    "Critical temperature";
  constant Modelica.Units.SI.Pressure   P_crit = 7.3773e6
    "Critical pressure";

  // NOTE — production deployment must redeclare the BaseProperties block
  // with table-lookup access to `tools/export_lut.py` output. The skeleton
  // below uses the parent IF97-style placeholder so OMC can compile the
  // package; do NOT use it for cycle calculations.

  redeclare model extends BaseProperties
    "Skeleton — replace with sco2_lut_openfoam.dat table interpolation"
  equation
    d = 800;            // PLACEHOLDER kg/m^3
    h = 4e5;            // PLACEHOLDER J/kg
    u = h - p/d;
    R_s = 188.9;
    MM  = 0.04401;
    state.T = T;
    state.p = p;
  end BaseProperties;

  annotation (Documentation(info="<html>
    <p>Bridge to the Phase 1 LUT generated by
    <code>src/tools/export_lut.py</code>. The skeleton hard-codes constants;
    replace <code>BaseProperties</code> with a 2-D table interpolation over
    <code>sco2_lut_openfoam.dat</code> before running cycle simulations.</p>

    <p>Reference: docs/03_phase3_modelica.md § 3.2 + docs/01 § 1.7.</p>
  </html>"));
end sCO2;
