"""Generate a self-consistency benchmark CSV from current CoolProp.

Reference: docs/01_phase1_properties.md § 1.6 + CI/CD section.

Why this exists
---------------
The headline benchmark for Phase 1 is *experimental data from Sandia /
STEP reports* (see ``data_sources.md``). Until those rows are
transcribed, an empty CSV makes the whole CI pipeline a no-op.

This script generates a *self-consistency* CSV that fills the same
schema with values produced by the currently installed CoolProp. It is
useful for two real things:

1. **Regression detection across CoolProp versions.** Re-run this script
   after every dependency bump. If ``validate_against_sandia.py`` then
   reports >0% relative error, CoolProp's CO2 EOS has changed numerically.
   That is information worth catching.
2. **Smoke-testing the validation pipeline.** Without it the pipeline
   has no rows to exercise — so a regression in
   ``validate_against_sandia.py`` itself would silently pass CI.

What this is NOT
----------------
**Not a substitute for experimental data.** A CSV produced this way only
proves CoolProp is consistent with itself, not that CoolProp is
consistent with reality. Rows produced here carry a clear source tag
(``coolprop_self`` instead of a Sandia/STEP citation) so they can never
be confused with real benchmark points.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import CoolProp.CoolProp as CP
import pandas as pd


# Operating points spanning the engineering window for sCO2 cycles.
# Selected to cover compressor inlet (305 K, ~7.7 MPa near pseudo-critical),
# heat-exchanger high-pressure side, and turbine inlet conditions.
SELF_CONSISTENCY_POINTS: list[tuple[float, float]] = [
    (305.4, 7.69e6),  # near pseudo-critical (Sandia compressor inlet shape)
    (308.0, 8.0e6),
    (320.0, 10.0e6),
    (351.2, 20.0e6),  # high-pressure side after compression
    (450.0, 20.0e6),
    (550.0, 20.0e6),
    (650.0, 20.0e6),
    (773.15, 20.0e6),  # turbine inlet (~500 °C)
    (823.15, 25.0e6),  # peak-cycle hot end
]


def build_dataframe(points: list[tuple[float, float]]) -> pd.DataFrame:
    rows = []
    for T, P in points:
        rows.append(
            {
                "T_inlet_K": T,
                "P_inlet_Pa": P,
                "T_outlet_K": "",
                "P_outlet_Pa": "",
                "rho_inlet_measured": CP.PropsSI("D", "T", T, "P", P, "CO2"),
                "efficiency_measured": "",
                "source_ref": "coolprop_self",
            }
        )
    return pd.DataFrame(rows)


def write_csv(df: pd.DataFrame, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    version = CP.get_global_param_string("version")
    header = [
        "# Self-consistency benchmark for sCO2 properties.",
        "#",
        f"# Generated by tools/build_self_consistency_csv.py against CoolProp {version}.",
        "# Source tag is 'coolprop_self' — these rows must never be cited as",
        "# experimental data. They exist purely to detect EOS regressions",
        "# across CoolProp versions and to keep the validation pipeline alive",
        "# until Sandia/STEP reports are transcribed.",
        "#",
        "# Columns mirror SNL_compressor_data.csv for drop-in compatibility.",
    ]
    with out_path.open("w") as f:
        f.write("\n".join(header) + "\n")
        df.to_csv(f, index=False)
    print(f"Wrote {out_path} ({len(df)} rows, CoolProp {version})")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument(
        "--out",
        type=Path,
        default=Path("validation/experimental_data/coolprop_self_consistency.csv"),
    )
    args = ap.parse_args()
    df = build_dataframe(SELF_CONSISTENCY_POINTS)
    write_csv(df, args.out)


if __name__ == "__main__":
    main()
