"""
sCO2 property look-up table (LUT) export.

Reference: docs/01_phase1_properties.md § 1.7

Phase 2 OpenFOAM needs property data for every mesh cell at every time step.
Calling CoolProp in real time would increase runtime by 10-100x.
Pre-generating an LUT is the standard engineering bridge to Phase 2.

Coverage rationale:
  - T 300-900 K (27-627 °C): compressor inlet through turbine outlet
  - P 7.5-25 MPa: low-pressure side through high-pressure side
  - 200x100 = 20 000 points balances accuracy and file size
"""

from __future__ import annotations

import argparse
from pathlib import Path

import CoolProp.CoolProp as CP
import numpy as np
import pandas as pd


def export_sco2_lut(
    T_min: float = 300.0,
    T_max: float = 900.0,
    P_min: float = 7.5e6,
    P_max: float = 25.0e6,
    n_T: int = 200,
    n_P: int = 100,
    output_prefix: str = "sco2_lut",
    fluid: str = "CO2",
) -> pd.DataFrame:
    """Generate a sCO2 property look-up table; write CSV + OpenFOAM .dat."""
    T_arr = np.linspace(T_min, T_max, n_T)
    P_arr = np.linspace(P_min, P_max, n_P)

    rows: list[dict[str, float]] = []
    skipped = 0
    for T in T_arr:
        for P in P_arr:
            try:
                rows.append(
                    {
                        "T": float(T),
                        "P": float(P),
                        "rho": CP.PropsSI("D", "T", T, "P", P, fluid),
                        "Cp": CP.PropsSI("C", "T", T, "P", P, fluid),
                        "mu": CP.PropsSI("V", "T", T, "P", P, fluid),
                        "k": CP.PropsSI("L", "T", T, "P", P, fluid),
                        "h": CP.PropsSI("H", "T", T, "P", P, fluid),
                    }
                )
            except Exception:
                skipped += 1

    df = pd.DataFrame(rows)
    csv_path = Path(f"{output_prefix}.csv")
    dat_path = Path(f"{output_prefix}_openfoam.dat")
    df.to_csv(csv_path, index=False)

    with dat_path.open("w") as f:
        f.write("// sCO2 property table generated by sco2-tmsr-toolkit\n")
        f.write("// Columns: T[K] p[Pa] rho[kg/m3] Cp[J/kgK] mu[Pa.s] k[W/mK]\n")
        for r in df.itertuples(index=False):
            f.write(
                f"{r.T:.2f} {r.P:.0f} {r.rho:.4f} {r.Cp:.2f} {r.mu:.6e} {r.k:.6f}\n"
            )

    print(f"LUT complete: {len(rows)} valid points, {skipped} skipped")
    print(f"Wrote: {csv_path}, {dat_path}")
    return df


def _build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate sCO2 LUT for OpenFOAM.")
    p.add_argument("--T-min", type=float, default=300.0)
    p.add_argument("--T-max", type=float, default=900.0)
    p.add_argument("--P-min", type=float, default=7.5e6)
    p.add_argument("--P-max", type=float, default=25.0e6)
    p.add_argument("--n-T", type=int, default=200)
    p.add_argument("--n-P", type=int, default=100)
    p.add_argument("--output-prefix", type=str, default="sco2_lut")
    p.add_argument("--fluid", type=str, default="CO2")
    return p


if __name__ == "__main__":
    args = _build_argparser().parse_args()
    export_sco2_lut(
        T_min=args.T_min,
        T_max=args.T_max,
        P_min=args.P_min,
        P_max=args.P_max,
        n_T=args.n_T,
        n_P=args.n_P,
        output_prefix=args.output_prefix,
        fluid=args.fluid,
    )
